; ===== Фракция: Lumeria =====
[Faction:LCA]
Description: Имперская Кирассирская Армия
Icon:https://i.imgur.com/placeholder_lumeria.png

Unit: LCA_shivul
Description: Пехотный отряд вооруженный револьверными винтовками и Щитами
Icon:https://i.imgur.com/beer_icon.png
Params: updateSlot2=1:Огнемёт

Unit: LCA_assaultSquad
Description: Отряд Штурмовиков
Icon:https://i.imgur.com/beer_icon.png
Params: updateSlot1=1:Усиленные Кирассы,updateSlot2=1:Дробовики

Unit: LCA_AT-Gat
Description: Легкий Колесный броневик с 2 пулеметами
Icon:https://i.imgur.com/beer_icon.png
Params: updateSlot2=1:Огнемёт

Unit: LCA_AT-45.20
Description: Легкий Колесный броневик с орудием
Icon:https://i.imgur.com/beer_icon.png



Description:Полевой медик, способный лечить союзников
Icon:https://i.imgur.com/medic_icon.png
Params:updateSlot1=1:Аптечка|2:Стимпак
